# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['**.Rmd']
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-renv@v1
      
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Install pacman
        run: Rscript -e 'install.packages("pacman")'
      - name: cache R packages 
        id: cache
        uses: actions/cache@v3.0.2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-
            
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          install.packages(c("lubridate", "tidyverse", "httr", "jsonlite", "stringr", "ggplot2", 
               "RColorBrewer", "cowplot", "zoo", "directlabels", "scales",
               "ggmap", "maps", "mapdata", "knitr"))
        shell: Rscript {0}
        
      - name: Render rapport
        run: Rscript -e 'rmarkdown::render("Corona-projekt.Rmd")'
      
      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit Corona-projekt.md -m 'Ny dag' || echo "Ny dag"
          git push origin || echo "Ny dag"

